// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmmedtmxvwazfxjbvbgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtbWVkdG14dndhemZ4amJ2YmdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDAzNzksImV4cCI6MjA2NTU3NjM3OX0.PE6Ni6ml4Sg4V0PlP4F3Y-LTV5GFgzV1Vrk7x_pr9Ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);